version: '3.8'

services:

  web:
    build:
      context: ./app
      dockerfile: app/Dockerfile
    ports:
      - "8764:8001"
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8001